### ISSUE TITLE
something wrong with the filters in looper 2

### ISSUE THREAD

**Issue by synthi** [andr-ew/gravl#1]
both the hp and lp filters don´t seem to have an effect in deck 2, working fine in 1. Ps awesome script, thanks!!

**Comment by synthi** [comment]
Testing some more: the parameters for the filter in looper 1 are a controlling both, and parameters on 2 does nothing

**Comment by andr-ew** [comment]
thx! should be fixed in the [latest release](https://github.com/andr-ew/grvl/releases/tag/v0.1.1-beta)

feel free to re-open if there's something I missed
